### ISSUE TITLE
False positive for xml tags

### ISSUE THREAD

**Issue by herloncf** [go-simpler/musttag#92]
I have the following structs:
```go
type XMLImage struct {
	XMLName xml.Name `xml:"image:image"`
	Loc     string   `xml:"image:loc"`
	Title   string   `xml:"image:title"`
}

type XMLAlternate struct {
	Rel      string `xml:"rel,attr"`
	HrefLang string `xml:"hreflang,attr"`
	Href     string `xml:"href,attr"`
}

type URL struct {
	XMLName xml.Name `xml:"url"`
	Loc     string   `xml:"loc"`
	LastMod string   `xml:"lastmod"`
	Image   *XMLImage
	Links   []XMLAlternate `xml:"xhtml:link"`
}

type XMLURLSet struct {
	XMLName    xml.Name `xml:"urlset"`
	Xmlns      string   `xml:"xmlns,attr"`
	XmlnsImage string   `xml:"xmlns:image,attr"`
	XmlnsXhtml string   `xml:"xmlns:xhtml,attr"`
	URL        []URL    `xml:"url"`
}
```

When I want to Marshal my `XMLURLSet`:
```go
	// Create new url set
	urlSet := &XMLURLSet{
		Xmlns:      "http://www.sitemaps.org/schemas/sitemap/0.9",
		XmlnsImage: "http://www.google.com/schemas/sitemap-image/1.1",
		XmlnsXhtml: "http://www.w3.org/1999/xhtml",
		URL:        myURLs,
	}

	// Encode chunk
	out, err := xml.Marshal(urlSet)
	if err != nil {
		return err
	}
```

I get the following error:
```
the given struct should be annotated with the `xml` tag (musttag)
        out, err := xml.Marshal(urlSet)
```

I can confirm that my xml output is exactly what I want. Am I doing something wrong?

Thanks.

**Comment by tmzane** [comment]
Hello,

Is it intentional that the `Image *XMLImage` field in the `URL` struct is not tagged? It seems that the complain is about it.

I get that `xml` allows naming with `XMLName xml.Name`, and this is exactly what you're doing here. Unfortunately, the linter knows nothing about semantics behind a specific marshaler, all it does is checking the existence of the tag.

IIRC, it would be produce the same output if you just fill the tag with the same name, like this: `Image *XMLImage xml:"image:image"`. Would that work for you?

**Comment by herloncf** [comment]
@tmzane is does seem to work fine. Sorry for the silly mistake 😅  and thank you!
